### ISSUE TITLE
Response times keep increasing

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis-service-armadillo#72] opened 2020-06-24 13:55 UTC
When letting multiple users login, load-tables and logout at roughly the same time, the load-tables request time keeps increasing, even between tests.

1. Tested with 50 users.
Response times keep ramping up. See the following image: sample times started at a few seconds

![image](https://user-images.githubusercontent.com/5362890/85567849-7cb34e80-b631-11ea-8f8b-8db5d2d7b81b.png)

2. Tested a few times with 50 users again.
Even after the previous requests have already returned and the sessions are closed, the sample times keep increasing.

It looks like Rserve is still busy doing something, even after the connection is closed.

**Comment by fdlk** [comment] 2020-07-23 16:14
This is definitely caused by the leftover processes on the server.

**Comment by fdlk** [comment] 2020-08-29 15:27
Fixed in Rserve

**Closed by fdlk** 2020-08-29 15:27 UTC
